### ISSUE TITLE
not turing complete

### ISSUE THREAD

**Issue by BlobTheKat** [MopBanana/NNYRLD#2]
This language is missing proper loops / goto
it is impossible to create many typical programs such as fibonacci or guess the number, nor is it possible to make a program that doesn't halt
**Possible solution:** replace `!!!!`'s functionality with _go back 10 instructions if value at the top of the stack is 0_

**Comment by BlobTheKat** [comment]
now the readme has an absolutely unforgivable typo (my name is spelled with a **<u>K</u>**)

**Comment by MopBanana** [comment]
> now the readme has an absolutely unforgivable typo (my name is spelled with a **K**)

So sorry, I will amend for this horrific act. Please accept this formal apology.

**Comment by openmc2d** [comment]
> > now the readme has an absolutely unforgivable typo (my name is spelled with a **K**)
> 
> So sorry, I will amend for this horrific act. Please accept this formal apology.

the gods of spelling & grammar are appeased

**Comment by BlobTheKat** [comment]
> So sorry, I will amend for this horrific act. Please accept this formal apology.

the gods of spelling & grammar are now appeased
